#

CC=gcc 
CFLAGS  = -DSOLARIS -threads
LDFLAGS = -lthread -L/usr/openwin/lib -lX11 -ldl -lrt -lm



aos.solaris:	clean aos.o Threads.solaris.o
	$(CC) -s -o aos.solaris aos.o Threads.solaris.o $(LDFLAGS)

aos.o:	aos.c
	$(CC) -c $(CFLAGS) aos.c

Threads.solaris.o:	Threads.h Threads.solaris.c
	$(CC) -c $(CFLAGS) Threads.solaris.c 

clean:
	rm -f *.o 

distclean:
	rm -f *.o aos.solaris*

